server:
  port: 8443
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/webshop-demo.westeurope.cloudapp.azure.com/keystore.p12
    key-store-password: changeit
    key-store-type: PKCS12
    key-alias: webshop-demo
spring:
  config:
    import: optional:file:.env[active=dev]
  application:
    name: webshop
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: "${SPRING_MAIL_PASSWORD}"
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  springdoc:
    swagger-ui:
      path: /swagger-ui.html
      enabled: true
    api-docs:
      path: /v3/api-docs
      enabled: true